import SwiftUI
import shared // Your KMP shared module

/// Bridges the Compose PayCraft paywall into SwiftUI
struct PaywallView: UIViewControllerRepresentable {
    func makeUIViewController(context: Context) -> UIViewController {
        // PaywallViewController() is generated by KMP Compose
        MainViewControllerKt.PaywallViewController()
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {}
}
