#!/usr/bin/env bash
# Generates JWT-signed anon + service_role keys for self-host PayCraft.
# Run once after editing .env, before docker compose up.
#
# Usage:
#   ./generate-keys.sh > .env.generated
#   cat .env.generated >> .env
set -euo pipefail

: "${PAYCRAFT_JWT_SECRET:=$(openssl rand -base64 32)}"

# Sign a JWT with the given role claim using HMAC-SHA256
sign_jwt() {
  local role="$1"
  local header='{"alg":"HS256","typ":"JWT"}'
  # 10-year expiry
  local exp=$(($(date +%s) + 315360000))
  local payload="{\"role\":\"$role\",\"iss\":\"supabase-self-hosted\",\"iat\":$(date +%s),\"exp\":$exp}"
  local header_b64=$(echo -n "$header" | openssl base64 -A | tr -d '=' | tr '/+' '_-')
  local payload_b64=$(echo -n "$payload" | openssl base64 -A | tr -d '=' | tr '/+' '_-')
  local sig=$(echo -n "${header_b64}.${payload_b64}" | openssl dgst -sha256 -hmac "$PAYCRAFT_JWT_SECRET" -binary | openssl base64 -A | tr -d '=' | tr '/+' '_-')
  echo "${header_b64}.${payload_b64}.${sig}"
}

echo "# Generated by generate-keys.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "PAYCRAFT_JWT_SECRET=${PAYCRAFT_JWT_SECRET}"
echo "PAYCRAFT_ANON_KEY=$(sign_jwt anon)"
echo "PAYCRAFT_SERVICE_ROLE_KEY=$(sign_jwt service_role)"
echo "PAYCRAFT_TOKEN_ENCRYPTION_KEY=$(openssl rand -hex 32)"
echo "PAYCRAFT_OAUTH_STATE_SECRET=$(openssl rand -hex 32)"
