package com.mobilebytelabs.paycraft.platform

/**
 * Provides platform identifier and human-readable device name for device binding.
 * Used in register_device() RPC and displayed in conflict resolution dialog.
 */
/**
 * What KIND of build the consuming app is, derived from the ARTIFACT'S OWN IDENTITY.
 *
 * The point of this type is that nobody declares it. Every earlier attempt to know test-vs-live
 * depended on something a human had to set and could forget — a `pk_test_`/`pk_live_` key prefix, a
 * `USE_TEST_BILLING` flag, a per-variant build field — and each one failed the same way: cappy's
 * opt-in was never set, so its debug builds shipped the LIVE key and could take real money in
 * development (`FAILURE_MODES.md` F35).
 *
 * A shipped application already PROVES what it is. An Android debug build is signed by the
 * universal debug keystore; an App Store build has no embedded provisioning profile. Those are
 * structural facts of how the platforms distribute software, not configuration. Reading them is
 * what makes correct behaviour the default instead of an instruction.
 *
 * [Unknown] is a first-class answer, not a failure. Where no honest signal exists the SDK says so
 * and reports [PlatformInfo.buildKindEvidence], rather than guessing — silence is precisely what
 * let F35 survive for months.
 */
enum class BuildKind { Debug, Release, Unknown }

expect object PlatformInfo {
    /** One of: "android" | "ios" | "macos" | "desktop" | "web" */
    val platform: String

    /** Human-readable name shown in conflict dialog, e.g. "Rajan's Pixel 8", "iPhone 15 Pro" */
    val deviceName: String

    /**
     * Stable hardware-unique identifier for same-device detection in register_device().
     * Never shown to users. Used exclusively for identity, not display.
     * Sources: ANDROID_ID (Android), identifierForVendor (iOS), NSUserDefaults UUID (macOS),
     *          persisted file UUID (JVM), localStorage UUID (JS/WasmJS).
     */
    val deviceId: String

    /**
     * ISO 3166-1 alpha-2 country code of the device's current region (e.g. "US", "IN"),
     * or null when undetectable. The SDK's device-side input to the single currency/country
     * decision point (PayCraft locale resolution): `InitOptions.localeOverride` wins, then
     * this, then the cloud config locale, then "US". Drives which per-locale price + which
     * per-currency provider checkout link is used.
     */
    val country: String?

    /**
     * What kind of build the CONSUMING APP is, read from the artifact itself. See [BuildKind].
     *
     * It must describe the HOST, not this library. A library's own `BuildConfig.DEBUG` reflects how
     * the AAR was compiled — always `false` in a published artifact — so reading it would report
     * every consumer as release, including the developer's own debug build. Every signal below is
     * therefore a property of the RUNNING APPLICATION:
     *
     * | platform | evidence | why it is trustworthy |
     * |---|---|---|
     * | Android | signing certificate subject — `CN=Android Debug` | the debug keystore is generated by the SDK tooling and never used to distribute |
     * | iOS | `embedded.mobileprovision` present / absent | an App Store binary structurally has no embedded profile |
     * | JVM/desktop | running from a packaged app-image vs `build/classes` | packaging is how a desktop app is shipped |
     * | JS / WasmJs | loopback origin vs a real one | a production bundle is not served from localhost |
     *
     * Android's signature check is strictly better than the `FLAG_DEBUGGABLE` it replaced: a RELEASE
     * build with `debuggable true` (routine for profiling) reads Debug under that flag and would be
     * handed the TEST key, silently taking no real payments. A signature cannot be confused that
     * way. It also no longer collapses to "release" when a startup race leaves the Context null —
     * that case is now [BuildKind.Unknown], which is visible.
     */
    val buildKind: BuildKind

    /**
     * Which signal produced [buildKind], e.g. `android:debug-keystore-signature`,
     * `ios:no-embedded-profile`, `jvm:unknown-no-packaging-signal`.
     *
     * Exists so a wrong answer is DIAGNOSABLE rather than mysterious, and so tooling
     * (`/idea-paycraft`) can assert that every target platform yields a determinate verdict instead
     * of discovering it on a device months later.
     */
    val buildKindEvidence: String

    /**
     * `true` when the consuming app is a debug build.
     *
     * Retained as a convenience over [buildKind] so existing callers keep compiling. Note the
     * collapse: both [BuildKind.Release] and [BuildKind.Unknown] read `false`, which is exactly the
     * ambiguity [buildKind] exists to expose — prefer [buildKind] in new code.
     */
    val isDebugBuild: Boolean
}
